BecomeTjunaFish.Lesson = DS.Model.extend({
  title: DS.attr('string'),
  progress: DS.attr('number'),
  img: DS.attr('string'),
  goal: DS.attr('string'),
  targetGroup: DS.attr('string'),
  prerequisites: DS.attr('string'),
  lesson_level: DS.attr('string'),
  lesson_time_indication: DS.attr('string'),
  lesson_url: DS.attr('string'),
  course: DS.belongsTo('Course', {async: true}),
  topics: DS.hasMany('Topic', {async: true}),
  lesson_authors: DS.hasMany('Authors', {async: true}),
  assignments: DS.hasMany('Assignment', {async: true})
});

BecomeTjunaFish.Lesson.FIXTURES = [
  {
    id: 1,
    title: 'HTML Basis',
    progress: 100,
    img: 'images/html_badge.png',
    goal: 'HTML basis concepten beheersen',
    targetGroup: 'frontend developers in wording',
    prerequisites: 'geen',
    lesson_level: 'Beginner',
    lesson_time_indication: '45 minuten',
    course: 1,
    topics: [1,2,3],
    lesson_authors: [1, 2],
    assignments: [1]
  },
  {
    id: 2,
    title: 'CSS Basis',
    progress: 25,
    img: 'images/css_badge.png',
    goal: 'Gebruik kunnen maken van CSS selectors, CSS positioning en margins en paddings',
    targetGroup: 'frontend developers in wording',
    prerequisites: 'geen',
    lesson_level: 'Beginner',
    lesson_time_indication: '30 minuten',
    topics: [4,5,6],
    lesson_authors: [3],
    course: 1,
    assignments: [2]
  },
  {
    id: 3,
    title: 'Conventies',
    progress: 0,
    img: 'images/conventies_badge.png',
    goal: 'De Tjuna conventies begrijpen en toe kunnen passen',
    targetGroup: 'frontend developers in wording',
    prerequisites: 'geen',
    lesson_level: 'Beginner',
    lesson_time_indication: '15 minuten',
    topics: [7,8],
    lesson_authors: [2,3],
    course: 1,
    assignments: [3]
  },
  {
    id: 4,
    title: 'Bugtracker',
    progress: 100,
    img: 'images/bug_badge.png',
    goal: 'bugs kunnen vinden in de bugtracker en bugs kunnen rapporteren',
    targetGroup: 'frontend developers in wording',
    prerequisites: 'geen',
    lesson_level: 'Beginner',
    lesson_time_indication: '20 minuten',
    topics: [9,10,11],
    lesson_authors: [1,4],
    course: 1,
    assignments: [4]
  },
  {
    id: 5,
    title: 'HTML5',
    progress: 0,
    goal: 'HTML5 elementen kennen en ze op de juiste manier toe kunnen passen',
    targetGroup: 'frontend developers in wording',
    prerequisites: 'HTML basis kennis',
    lesson_level: 'Gevorderd',
    lesson_time_indication: '40 minuten',
    topics: '',
    lesson_authors: [1,3],
    course: 2,
    assignments: ''
  },
  {
    id: 6,
    title: 'CSS3',
    progress: 0,
    goal: 'CSS3 user interface elementen toe kunnen passen',
    targetGroup: 'frontend developers in wording',
    prerequisites: 'CSS basis kennis',
    lesson_level: 'Gevorderd',
    lesson_time_indication: '60 minuten',
    topics: '',
    lesson_authors: [2,3],
    course: 2,
    assignments: ''
  },
  {
    id: 7,
    title: 'jQuery',
    progress: 0,
    goal: 'de DOM aan kunnen passen met jQuery',
    targetGroup: 'frontend developers in wording',
    prerequisites: 'HTML en CSS basis kennis',
    lesson_level: 'Gevorderd',
    lesson_time_indication: '60 minuten',
    topics: '',
    lesson_authors: [2,3],
    course: 2,
    assignments: ''
  },
  {
    id: 8,
    title: 'PHP',
    progress: 0,
    goal: 'Simpele PHP pagina op kunnen zetten',
    targetGroup: 'backend developers in wording',
    prerequisites: 'HTML en CSS basis kennis',
    lesson_level: 'Gevorderd',
    lesson_time_indication: '40 minuten',
    topics: '',
    lesson_authors: [2,3],
    course: 3,
    assignments: ''
  },
  {
    id: 9,
    title: 'MySQL',
    progress: 0,
    goal: 'Een MySQL database met verschillende tabellen aan kunnen maken',
    targetGroup: 'backend developers in wording',
    prerequisites: 'geen',
    lesson_level: 'Gevorderd',
    lesson_time_indication: '60 minuten',
    topics: '',
    lesson_authors: [2,3],
    course: 3,
    assignments: ''
  },
  {
    id: 10,
    title: 'CodeIgniter',
    progress: 0,
    goal: 'CodeIgniter MVC begrijpen en model, view, controller in een simpel voorbeeld toe kunnen passen',
    targetGroup: 'backend developers in wording',
    prerequisites: 'PHP en SQL basis kennis',
    lesson_level: 'Gevorderd',
    lesson_time_indication: '60 minuten',
    topics: '',
    lesson_authors: [2,3],
    course: 3,
    assignments: ''
  },
  {
    id: 11,
    title: 'Tjuna Albacore CMS',
    progress: 0,
    goal: 'simpel CMS op kunnen zetten met Albacore en modules aan kunnen maken',
    targetGroup: 'backend developers in wording',
    prerequisites: 'PHP, SQL en CodeIgniter',
    lesson_level: 'Gevorderd',
    lesson_time_indication: '90 minuten',
    topics: '',
    lesson_authors: [2,3],
    course: 3,
    assignments: ''
  }

];
